language: python
python:
- 3.7
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: willyheng
  password:
    secure: V6F5hMfpMGlOBIuuGTnqcAHETaPS+JXBDkdI6ylK1pLlQhSXCVQYpsAi0ebkkQz30Dz6W+300EkjyooF2kETADUeotM8JYHVHLZ1cbayRDdf8DtjSZu1cPUDo+sbQ+8fkCYEVuANaQFUmFFVd0teC49u8ywWxog8kNk7pgUDrDaMR/ebcaM0wceBiqNTVRuuYDcUGW76lqdwFgt65M8+nNxrlOMUs68KnXUqybvmhwtMNeduMdZN4/B+4w+yZPHjJnJ23hCLXe9crL1n2RrNOoirhd9l+0netyJ1qAwrCTWt3JJecdU4U3yJPe7y8huFpLCzU1YfXnPC/8C6NHZikRUNc5N/DqbGvvQYVHnfqbc97CDJuiOU44lmTfL3OIIa5ZR8P/1kORXe6d7kK6Mr3j7P723OMCcRLv1Be4jytIEEAzVelSK4x7OCJ9Jk5iC+MSPDlQc7d2doS3RVy3qTWfdA/gAjAfCJPfS6dv4bwSsP2QRzQgHouI6/nU/jSEpRI1VRd4/V7C+fDHP8Dez0k7oOJBucen+WAphxr8ICN+X8ImOD7XeiLvVLisx1J4Pk+8+JkItFN1J19UZsKEu5H8zIuIF0fN0pmyLB/UKLGIYf4oaFs/ASUXpgE5TPVecIdWzCXGkIDVF86P/Wf9/UpB4jlpYEz7XrRLWrdDWON8w=
  on:
    tags: true
    repo: willyheng/sampy
    python: 3.7
